### ISSUE TITLE
comment on type checks

### ISSUE THREAD

**Issue by godfrey-scalpel** [SciFin-Team/SciFin#1]
1) you can put the types of the arguments in the function as well. In that case, IDE like PyCharm can auto-detect if certain input arguments are of incorrect type while you are writing the codes. You can also do that for output

For instance,
-------------------
def euclidean_distance(
    ts1: TimeSeries, 
    ts2: TimeSeries
) -> float:
------------
   
2) Also, for type checking, instead of adding an extra class attribute for type check, you can just simply use
isinstance(ts1, TimeSeries) instead. 

Also, you can use decorators from existing libraries like typeguard for that (as long as you put the input and output types when defining the function as above), see https://typeguard.readthedocs.io/en/latest/userguide.html

(However, beware that type-checking can significantly slow down efficiency of your codes for large projects. So in some cases, might be worth just use try and except to catch and raise any incorrect type issues)

3) For Dynamic Time Warping (DTW) distance function, why set the window size as the length of the second time series if it is not given?  Shouldn't it be the min of the 2 input series?

**Comment by FabienNugier** [comment]
Thanks Godfrey and sorry for the late in my reply.
1. Typing is really interesting. It is good practice and I am going to introduce it gradually into the development.
2. Thanks for the tips, indeed testing TimeSeries is very useful. As for typeguard, this deserves more investigation.
3. I think you're right, it should probably be the minimum. Changes will be done soon after checking.
Thanks again!

**Comment by FabienNugier** [comment]
Regarding point 3. I think the window's minimal size is abs(N2-N1) (with N1, N2 the size of the two series). Hence we should take w = max(window, abs(N2-N1)).
